package cep::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'cep::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:dbname=cep',
        user => 'opendatabr',
        password => 'kdos94m3',
    }
);

=head1 NAME

cep::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<cep>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Hertz::Model::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.43

=head1 AUTHOR

Thiago Rondon

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
